# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  desc "Build a release version of the app"

  lane :build_release do
    create_keychain(
      name: "com.wildlife.wildlifewatcher",
      password: ENV["IOS_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )
    
    install_provisioning_profile(path: "./fastlane/profile.mobileprovision")

    import_certificate(
      keychain_name: "com.wildlife.wildlifewatcher",
      keychain_password: ENV["IOS_KEYCHAIN_PASSWORD"],
      certificate_path: "./fastlane/cert.p12",
      certificate_password: ENV["IOS_CERT_PASSWORD"]
    )

    ios_set_version(
      version: ENV["APP_VERSION"],
      xcodeproj: "./ios/WildlifeWatcher.xcodeproj"
    )

    build_ios_app(
      silent: true,
      scheme: 'WildlifeWatcher', 
      configuration: "Release",
      workspace: './ios/WildlifeWatcher.xcworkspace', 
      output_directory: './ios/ipa', 
      output_name: 'WildlifeWatcher.ipa',
      buildlog_path: './ios/logs',
      xcargs: "-allowProvisioningUpdates",
      suppress_xcode_output: true,
      export_options: "./ios/WildlifeWatcher/exportOptions.plist"  
    )

    firebase_app_distribution(
      app: ENV["APP_ID_IOS"],
      service_credentials_file: "./fastlane/wildlife-watcher-service-account.json",
      testers: ENV['TESTERS']
    )
  end
end
platform :android do
  desc "Build a release version of the app"
  lane :build_release do
    android_set_version_name(
      version_name: ENV["APP_VERSION"],
      gradle_file: './android/app/build.gradle'
    )

    android_set_version_code(
      version_code: ENV['APP_CODE_VERSION'],
      gradle_file: './android/app/build.gradle'
    )
    
    gradle(
      project_dir: "./android",
      task: "assemble",
      build_type: "Release"
    )

    firebase_app_distribution(
      app: ENV["APP_ID"],
      android_artifact_path: "./android/app/build/outputs/apk/release/app-release.apk",
      service_credentials_file: "./fastlane/wildlife-watcher-service-account.json",
      testers: ENV['TESTERS']
    )

    upload_to_play_store(
      json_key: "./fastlane/wildlife-watcher-service-account.json",
      release_status: 'draft',
      track: 'internal',
      apk_paths: './android/app/build/outputs/apk/release/app-release.apk'
  )
  end
end