# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  desc "Build a release version of the app"

  lane :build_release do

    # Check if the release_notes.txt file exists
    if File.exist?("./release_notes.txt")
      # Read the contents of the file
      release_notes_content = File.read("./release_notes.txt")
      
      # Print the contents of the file
      puts "Release Notes:"
      puts release_notes_content
    else
      puts "Release notes file not found"
      puts "Current directory: #{Dir.pwd}"
      puts "Files in current directory: #{Dir.entries(".")}"
    end

    create_keychain(
      name: "com.wildlife.wildlifewatcher",
      password: ENV["IOS_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )
    
    import_certificate(
      keychain_name: "com.wildlife.wildlifewatcher",
      keychain_password: ENV["IOS_KEYCHAIN_PASSWORD"],
      certificate_path: "./fastlane/cert.p12",
      certificate_password: ENV["IOS_CERT_PASSWORD"]
    )

    ios_set_version(
      version: ENV["APP_VERSION"],
      xcodeproj: "./ios/WildlifeWatcher.xcodeproj"
    )

    ios_set_build_number(
      build_number: ENV['APP_CODE_VERSION'],
      xcodeproj: "./ios/WildlifeWatcher.xcodeproj"
    )

    install_provisioning_profile(path: "./fastlane/testers.mobileprovision")
    install_provisioning_profile(path: "./fastlane/profile.mobileprovision")

    build_ios_app(
      silent: true,
      scheme: 'WildlifeWatcher', 
      configuration: "Release",
      workspace: './ios/WildlifeWatcher.xcworkspace', 
      output_directory: './ios/ipa', 
      output_name: 'WildlifeWatcher.ipa',
      buildlog_path: './ios/logs',
      suppress_xcode_output: true,
      export_options: "./ios/WildlifeWatcher/exportOptionsTesters.plist"  
    )

    firebase_app_distribution(
      app: ENV["APP_ID"],
      service_credentials_file: "./fastlane/wildlife-watcher-service-account.json",
      testers: ENV['TESTERS'],
      release_notes_file: './release_notes.txt'
    )

    build_ios_app(
      silent: true,
      scheme: 'WildlifeWatcher', 
      configuration: "Release",
      workspace: './ios/WildlifeWatcher.xcworkspace', 
      output_directory: './ios/ipa', 
      output_name: 'WildlifeWatcher.ipa',
      buildlog_path: './ios/logs',
      suppress_xcode_output: true,
      export_options: "./ios/WildlifeWatcher/exportOptions.plist"  
    )

    # Should upload to testflight at this point
  end
end
platform :android do
  desc "Build a release version of the app"
  lane :build_release do
    android_set_version_name(
      version_name: ENV["APP_VERSION"],
      gradle_file: './android/app/build.gradle'
    )

    android_set_version_code(
      version_code: ENV['APP_CODE_VERSION'],
      gradle_file: './android/app/build.gradle'
    )
    
    gradle(
      project_dir: "./android",
      tasks: ["assembleRelease", "bundleRelease"]
    )

    firebase_app_distribution(
      app: ENV["APP_ID"],
      android_artifact_path: "./android/app/build/outputs/apk/release/app-release.apk",
      service_credentials_file: "./fastlane/wildlife-watcher-service-account.json",
      testers: ENV['TESTERS'],
      release_notes_file: './release_notes.txt'
    )
    
    # Will add once the app is uploaded
    # upload_to_play_store(
    #   json_key: "./fastlane/wildlife-watcher-service-account.json",
    #   release_status: 'draft',
    #   track: 'internal',
    #   aab: './android/app/build/outputs/bundle/release/app-release.aab'
    # )
  end
end